### ISSUE TITLE
Benchmark with other xlsxwriter libraries

### ISSUE THREAD

**Issue by haritsfahreza** [expedock/pyaccelsx#1]
I would be pleased if you could provide how fast `pyaccelsx` is compared to notable other python xlsx writer such as `xlsxwriter` and `openpyxl`. It would be great also to highlight the CPU and memory usage during the comparison. Thanks!

**Comment by jmcnamara** [comment]
Here are some performance tests to compare against rust_xlsxwriter and XlsxWriter (and libxlsxwriter if needed). 

https://rustxlsxwriter.github.io/performance.html

**Comment by stanleysie** [comment]
Added some initial performance tests and time comparison against `rust_xlsxwriter`, `Xlsxwriter`, and `openpyxl` in this [PR](https://github.com/expedock/pyaccelsx/pull/6) 🙂 

Will look further into how we can reliably measure cpu and memory usage for comparison. There is [poop](https://github.com/andrewrk/poop) that we can possibly use for this but need further investigation if it's possible.

**Comment by haritsfahreza** [comment]
Thankyou @stanleysie, will close this issue as it's resolved!
